version: 1
accounts:
- name: doxcfoundation
  coins:
  - 20000token
  - 200000000stake
- name: beheroes
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: beheroes
  coins:
  - 5token
  - 100000stake
validators:
- name: doxcfoundation
  bonded: 100000000stake
